{{- $labels := include "kubedeploy.labels" . -}}
{{- if gt (len .Values.configMaps) 0 -}}
{{- range $index, $configMap := .Values.configMaps }}
{{- $name := include "kubedeploy.cfgmapname" (list $ $configMap) -}}
{{- if $index }}
---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    {{- $labels | nindent 4 }}
data:
{{- $configMap.data | default ""| toYaml | nindent 2}}
{{ end }}
{{- end }}
