{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubedeploy.fullname" . }}
  labels:
    {{- include "kubedeploy.labels" . |nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kubedeploy.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if gt (len .Values.networkPolicy.ingress) 0 }}
    - Ingress
    {{- end }}
    {{- if gt (len .Values.networkPolicy.egress) 0 }}
    - Egress
    {{- end }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
