{{- $labels := include "kubedeploy.labels" . -}}
{{- if gt (len .Values.extraSecrets) 0 -}}
{{- range $index, $secret := .Values.extraSecrets }}
{{- $name := include "kubedeploy.secretname" (list $ $secret) -}}
{{- if $index }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- $labels | nindent 4 }}
type: {{ default "Opaque" $secret.type }}
data:
{{- range $key, $value := $secret.data }}
  {{ $key }}: {{ printf "%s" $value | b64enc | quote }}
{{- end }}
{{ end }}
{{- end }}
