{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubedeploy.fullname" . }}
  labels:
    {{- include "kubedeploy.labels" . | nindent 4 }}
spec:
  {{- if .Values.service.headless }}
  clusterIP: "None"
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.service.ports }}
  {{- with .Values.service.ports }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else if .Values.ports }}
  {{- range $port := .Values.ports }}
    - port: {{ required "You must define at least containerPort in .Values.ports[]" $port.containerPort }}
      {{- with $port.name }}
      targetPort: {{ . }}
      name: {{ . }}
      {{- end }}
      {{- with $port.protocol }}
      protocol: {{ . }}
      {{- end }}
  {{- end }}
  {{- else -}}
  {{/* This is here for legacy reasons TODO: remove in v2.x */}}
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  {{- end }}
  selector:
    {{- include "kubedeploy.selectorLabels" . | nindent 4 }}
{{- end }}
