kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: build
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-pv-claim
  namespace: build
spec:
  storageClassName: build
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
#这个yaml文件是为每次动态生成的pod的缓存使用的
