{{ $global := . }}
{{- range $key, $value := .Values.server }}
{{- if $value.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "roh5server.fullname" $global }}-{{ $key    }}
  namespace: roh5server
  labels:
    {{- include "roh5server.labels" $global | nindent 4 }}-{{ $key   }}
spec:
  replicas: {{ $global.Values.replicas }}
  selector:
    matchLabels:
      {{- include "roh5server.selectorLabels" $global | nindent 6 }}-{{ $key   }}
      game-svc: "game-svc-{{ $key  }}"
  template:
    metadata:
      labels:
        {{- include "roh5server.selectorLabels" $global | nindent 8 }}-{{ $key  }}
        game-svc: "game-svc-{{ $key   }}"
      annotations:
        eks.tke.cloud.tencent.com/registry-insecure-skip-verify: "lb-etkxh0j3-azlwq5ic9dpkotm4.clb.ap-shanghai.tencentclb.com:5000"
    spec:
      imagePullSecrets:
      - name: auth-registry-secret
      initContainers:
      - image: busybox
        command:
        - sh
        - -c
        - |
          sysctl -w net.core.somaxconn=65535
          sysctl -w net.ipv4.ip_local_port_range="1024 65535"
          sysctl -w net.ipv4.tcp_tw_reuse=1
          sysctl -w fs.file-max=1048576
        imagePullPolicy: Always
        name: setsysctl
        securityContext:
          privileged: true
      containers:
      - name: {{ $global.Chart.Name }}
        image: "{{ $global.Values.image.repo }}{{ .image }}:{{ .tag }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: SID
          value: {{ $key  | quote }}
        - name: TZ
          value: "Asia/Jakarta"
        - name: start
          value: {{ .start  |quote }}
        - name: thread
          value: {{ .thread  |quote}}
        - name: MAXRPCAGENT
          value: {{ .MAX_RPC_AGENT |quote}}
        resources:
          limits:
            cpu: 4000m
            memory: 8000Mi
          requests:
            cpu: 200m
            memory: 300Mi
        ports:
        - containerPort: 10002
          name: server1
          protocol: TCP
        - containerPort: 10003
          name: server2
          protocol: TCP
        - containerPort: 10004
          name: server3
          protocol: TCP
        - containerPort: 10007
          name: server4
          protocol: TCP
        - containerPort: 10010
          name: server5
          protocol: TCP
        volumeMounts:
        - name: game-log
          mountPath: "/usr/data/svr/log/main_logic" 
        - name: config
          mountPath: "/usr/data/svr/main_logic_real"
          subPath: main_logic_real
          readOnly: false
      volumes:
      - name: game-log
        hostPath:
          # Ensure the file directory is created.
          path: /var/local/game-log-{{ $key    }}
          type: DirectoryOrCreate
      - name: config
        configMap:
          # 提供你想要挂载的 ConfigMap 的名字
          name: roh5server-cm-main
          #defaultMode: 0777 
          # 来自 ConfigMap 的一组键，将被创建为文件
          items:
          - key: "main_logic_real"
            path: "main_logic_real"
{{- end }}
---
{{- end }}
