apiVersion: game.kruise.io/v1alpha1
kind: GameServerSet  
metadata:
  name: roh5server-9903
  namespace: roh5server
  labels:
    app.kubernetes.io/name: roh5server
spec:
  replicas: 1
  updateStrategy:
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
  network:
    networkConf:
    - name: IngressClassName
      value: roh5server
    - name: Port
      value: "10002"
    - name: Path
      value: /s9003<id>(/|$)(.*)
    - name: Host
      value: roh5server.k8s.com
    - name: PathType
      value: ImplementationSpecific
    - name: Port
      value: "10003"
    - name: Port
      value: "10004"
    - name: Port
      value: "10007"
        #- name: TlsHosts
        #value: sandbox.k8s.xinghuihuyu.cn
        #- name: TlsSecretName
        #value: sandbox-k8s-secret
    - name: Annotation
      value: 'nginx.ingress.kubernetes.io/rewrite-target: /$2'
    - name: Annotation
      value: 'nginx.ingress.kubernetes.io/use-regex: "true"'
    - name: Annotation
      value: 'kubernetes.io/ingress.existLbId: lb-nsmn26mh'

    networkType: Kubernetes-Ingress
  gameServerTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: roh5server
      annotations:
        eks.tke.cloud.tencent.com/registry-insecure-skip-verify: "lb-rj0l4baf-zc9g164t8j7pamlq.clb.ap-shanghai.tencentclb.com:5000"
    spec:
      imagePullSecrets:
      - name: auth-registry-secret
      initContainers:
      - name: myapp
        image: alpine:latest
        command: ["sh", "-c"]
        args:
        - echo "$MY_POD_NAME" |awk -F '-' '{print $2,$3}'  |sed  's/ //' > /opt/pod.txt  && sleep '1'
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: data
          mountPath: /opt
      containers:
      - name: roh5server-game
        image: "lb-rj0l4baf-zc9g164t8j7pamlq.clb.ap-shanghai.tencentclb.com:5000/k8s-roh5server:v6"
        imagePullPolicy: Always
        command: ['bash', '-c']
        args:
        - './start.sh'
          #- sleep '99999'
        env:
        #  - name: DEBUG
        #    value: "true"
        #  - name: GM
        #    value: "1"
        #  - name: SID
        #    value: "99050"
        ports:
        - name: server1
          containerPort: 10002
        - name: server2
          containerPort: 10003
        - name: server3
          containerPort: 10004
        - name: server4
          containerPort: 10007
        volumeMounts:
        - name: data
          mountPath: /opt
        - name: config
          mountPath: "/usr/data/svr/main_logic_real"
          subPath: main_logic_real
          readOnly: false
        - name: config
          mountPath: "/usr/data/svr/start.sh"
          subPath: start.sh
          readOnly: false        
      volumes:
      - name: data
        emptyDir: {}  
      - name: config
        configMap:
          # 提供你想要挂载的 ConfigMap 的名字
          name: roh5server-cm
          defaultMode: 0777 
          # 来自 ConfigMap 的一组键，将被创建为文件
          items:
          - key: "main_logic_real"
            path: "main_logic_real"
          - key: "start.sh"
            path: "start.sh"
