apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-intact
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision-tag
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: trigger-build-push-and-deploy-run-
      spec:
        serviceAccountName: push-image
        pipelineRef:
          name: build-push-and-deploy-pipeline
        podTemplate:
          securityContext:
            fsGroup: 1001
        params:
          - name: gitrevision-tag
            value: $(tt.params.gitrevision-tag) #This value will be passed from trigger binding.			
          - name: repo-url
            value: http://gitlab.x.xinghuihuyu.cn/flux-cd/tekton-nodejs-sample.git
          - name: image-reference
            value: harbor.forcecs.com:32415/tekton/nodejs-sample:v3
          - name: charts_dir
            value: helm/nodejs-welcome
          - name: tag
            value: v3
          - name: release_name
            value: "nodejs-example-trigger"
          - name: values_file
            value: "values.yaml"
          - name: release_namespace
            value: "tekton-pipelines"
        workspaces:
        - name: shared-data
          persistentVolumeClaim:
            claimName: triggers-pvc
        - name: git-credentials
          secret:
            secretName: git-credentials
        - name: docker-credentials
          secret:
            secretName: docker-credentials
