{{ $global := . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "middle.fullname" $global }}-svc
  labels:
    {{- include "middle.labels" $global | nindent 4 }}
    game-svc: "game-svc-{{ $global.Chart.Name }}"
spec:
  type: {{ $global.Values.service.type }}
  ports:
  - name: "game-svc-1"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "middle.selectorLabels" $global | nindent 4 }}
    game-svc: "game-svc-{{ $global.Chart.Name }}"

