apiVersion: v1
kind: Service
metadata:
  name: jenkins-service-jnlp
  namespace: jenkins
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '50000'
spec:
  selector:
    app: jenkins-server
  type: NodePort
  ports:
    - port: 50000
      targetPort: 50000
      nodePort: 32001
