apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: hdh5
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30006
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: hdh5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'xxxxxxxxx'
        - name: TZ
          value: 'Asia/Shanghai'
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: hdh5-mysql-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: hdh5-mysql-pv 
        persistentVolumeClaim:
          claimName: hdh5-mysql-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdh5-mysql-pv
  labels:
    type: local
spec:
  storageClassName: hdh5
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/proj/hdh5/mysql-5.7/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdh5-mysql-pvc
  namespace: hdh5
spec:
  storageClassName: hdh5
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
