apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
  namespace: roh5server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      initContainers:
        - name: auth
          image: httpd:2
          command: ["sh", "-c", "htpasswd  -Bbn  local local.com123  >  /auth/htpasswd"]
          volumeMounts:
            - name: data
              mountPath: /auth
      containers:
        - name: registry
          image: registry:2
          ports:
          - containerPort: 5000
            name: registry-port
          env:
          - name: REGISTRY_AUTH
            value: "htpasswd"
          - name: REGISTRY_AUTH_HTPASSWD_REALM
            value: "Registry Realm"
          - name: REGISTRY_AUTH_HTPASSWD_PATH
            value: /auth/htpasswd
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: /certs/tls.crt
          - name: REGISTRY_HTTP_TLS_KEY
            value: /certs/tls.key
          volumeMounts:
            - name: data
              mountPath: /auth
            - name: secret-volume
              readOnly: true
              mountPath: "/certs"
      volumes:
        - name: data
          emptyDir: {}
        - name: secret-volume
          secret:
            secretName: registry-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: roh5server
spec:
  selector:
    app: registry
  ports:
  - name: registry-service-port
    protocol: TCP
    port: 5000
    nodePort: 31745
    targetPort: registry-port
  type: LoadBalancer
