apiVersion: v1
kind: Secret
type: kubernetes.io/ssh-auth
metadata:
  name: git-credentials
  annotations:
    tekton.dev/git-0: http://gitlab.forcemcs.cn
type: kubernetes.io/basic-auth
stringData:
  username: <明文user>
  password: <明文passwd>
  #有关更安全的方式请自行参考官方项目演示
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-bot
secrets:
  - name: git-credentials
