apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: demo-service-alter
  namespace: monitoring
  labels:
    alertmanagerConfig: demo-service-alter
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanagerconfig
    app.kubernetes.io/part-of: kube-prometheus
    
spec:
  route:
    # Group alerts with the same alert name and job into one notification.
    groupBy: ['alertname', 'job']
    
    #continue: false
  
    # Wait 30s before sending the initial notification for a group.
    groupWait: 30s
    # Wait 5m before sending follow-up notifications for new alerts in a group.
    groupInterval: 2m
    # Wait 3h before repeating the same notification again.
    repeatInterval: 3h
  
    # By default, send notifications to team A's Slack channel.
    receiver: server-team
  
    # Child routes with job-specific matchers & overrides.
    routes:
    - matchers:
      - matchType: =
        name: alertname
        value: DemoServiceHighErrorRate
      receiver: server-team
      # Child route 1. Match alerts for job="job-a".
        # Send these alerts to team A's Slack channel...

  
  # Named receivers defining how to send notifications to a destination.
  receivers:
  - name: server-team
    slackConfigs:
    - channel: '#alerts'
      # Also send notifications for resolved alerts.
      apiURL:
        key: slack_webhook
        name: alertmanager-slack-notification
      sendResolved: true
      # A message title that shows a summary of the alerts.
      title: |-
        [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
        {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
          {{" "}}(
          {{- with .CommonLabels.Remove .GroupLabels.Names }}
            {{- range $index, $label := .SortedPairs -}}
              {{ if $index }}, {{ end }}
              {{- $label.Name }}="{{ $label.Value -}}"
            {{- end }}
          {{- end -}}
          )
        {{- end }}
      # The message body that shows full label and annotation details for all alerts.
      text: >-
        {{ with index .Alerts 0 -}}
          :chart_with_upwards_trend: *<{{ .GeneratorURL }}|Graph>*
        {{ end }}
  
        *Alert details*:
  
        {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
        *Description:* {{ .Annotations.description }}
        *Details:*
          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        {{ end }}
