apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "roh5server.fullname" . }}
  namespace: roh5server
  labels:
    {{- include "roh5server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "roh5server.selectorLabels" . | nindent 6 }}
      game-svc: "game-svc-{{ .Values.env.SID }}"
  template:
    metadata:
      labels:
        {{- include "roh5server.selectorLabels" . | nindent 8 }}
        game-svc: "game-svc-{{ .Values.env.SID }}"
      annotations:
        eks.tke.cloud.tencent.com/registry-insecure-skip-verify: "xxxx.com:5000"
    spec:
      imagePullSecrets:
      - name: auth-registry-secret
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        env:
        {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value   | quote }}
        {{- end }}
        ports:
        - containerPort: 10002
          name: server1
          protocol: TCP
        - containerPort: 10003
          name: server2
          protocol: TCP
        - containerPort: 10004
          name: server3
          protocol: TCP
        - containerPort: 10007
          name: server4
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: "/usr/data/svr/main_logic_real"
          subPath: main_logic_real
          readOnly: false
      volumes:
      - name: config
        configMap:
          # 提供你想要挂载的 ConfigMap 的名字
          name: roh5server-cm
          #defaultMode: 0777 
          # 来自 ConfigMap 的一组键，将被创建为文件
          items:
          - key: "main_logic_real"
            path: "main_logic_real"
