apiVersion: v1
kind: Service
metadata:
  name: {{ include "roh5server.fullname" . }}
  namespace: roh5server
  labels:
    {{- include "roh5server.labels" . | nindent 4 }}
    game-svc: "game-svc-{{ .Values.env.SID }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "game-svc-1"
    port: 10002
    protocol: TCP
    targetPort: 10002
  - name: "game-svc-2"
    port: 10003
    protocol: TCP
    targetPort: 10003
  - name: "game-svc-3"
    port: 10004
    protocol: TCP
    targetPort: 10004
  - name: "game-svc-4"
    port: 10007
    protocol: TCP
    targetPort: 10007
  selector:
    {{- include "roh5server.selectorLabels" . | nindent 4 }}
    game-svc: "game-svc-{{ .Values.env.SID }}"
