apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=/workspace/dockerfile",
            "--context=dir://workspace",
            #"--insecure",
            "--skip-tls-verify",
            "--destination=harbor.forcecs.com:32415/kubernetes/testtttttt:v4"] # replace with your dockerhub account
    volumeMounts:
      - name: dockerfile-storage
        mountPath: /workspace
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: kaniko-pvc
