FROM ubuntu:22.04 as builder


WORKDIR /script
COPY . .

WORKDIR /app/config
RUN rm -rf lua \
    && chmod +x ./xlsx_trans.linux \
    && mkdir lua \
    && mkdir lua/scene_data \
    && mkdir lua/maze_map \
    && mkdir lua/scripts \
    && ./xlsx_trans.linux ./ ./lua/ \
    && cp -r scene_data/* lua/scene_data/ \
    && cp -r maze_map_lua/* lua/maze_map/ \
    && cp -r scripts/* lua/scripts/

WORKDIR /app/protobuf
RUN rm -rf .cache \
    && ./protobufmake.linux  

FROM ubuntu:22.04

USER root

ENV TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive

RUN sed -i "s@http://.*archive.ubuntu.com@http://mirrors.huaweicloud.com@g" /etc/apt/sources.list  \
    &&  sed -i "s@http://.*security.ubuntu.com@http://mirrors.huaweicloud.com@g" /etc/apt/sources.list \
    &&  apt-get update && apt-get install -y inotify-tools curl  


#RUN   ln -sv /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
#      &&  echo "Asia/Shanghai" > /etc/timezone \
#      &&  dpkg-reconfigure --frontend noninteractive tzdata 


RUN apt update \
    && apt install -y tzdata \
    && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*


COPY --from=builder /app/server /usr/data/bin
COPY --from=builder /app/protobuf/.cache /usr/data/protobuf
COPY --from=builder /app/config/lua /usr/data/config
COPY --from=builder /app/env /usr/data/svr/

WORKDIR /usr/data/svr

EXPOSE  10002
EXPOSE  10003
EXPOSE  10004
EXPOSE  10007
ENTRYPOINT [ "../bin/skynet/skynet", "main_logic_real" ]
