server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: nginx
  static_configs:
    - targets:
        - localhost
      labels:
        job: nginx
        __path__: /var/log/nginx/*.log
- job_name: roh5server
  static_configs:
  - targets:
      - localhost
    labels:
      job: roh5server
      __path__: /var/lib/docker/containers/0ec04a35de78*/*log

