{{ $global := . }}
{{- range $key, $value := .Values.env.SID }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "roh5server.fullname" $global }}-{{ $value    }}
  namespace: roh5server
  labels:
    {{- include "roh5server.labels" $global | nindent 4 }}-{{ $value   }}
spec:
  replicas: {{ $global.Values.replicas }}
  selector:
    matchLabels:
      {{- include "roh5server.selectorLabels" $global | nindent 6 }}-{{ $value   }}
      game-svc: "game-svc-{{ $value  }}"
  template:
    metadata:
      labels:
        {{- include "roh5server.selectorLabels" $global | nindent 8 }}-{{ $value  }}
        game-svc: "game-svc-{{ $value   }}"
      annotations:
        eks.tke.cloud.tencent.com/registry-insecure-skip-verify: "lb-rj0l4baf-zc9g164t8j7pamlq.clb.ap-shanghai.tencentclb.com:5000"
    spec:
      imagePullSecrets:
      - name: auth-registry-secret
      containers:
      - name: {{ $global.Chart.Name }}
        image: "{{ $global.Values.image.repo }}:{{ $global.Values.image.tag }}"
        imagePullPolicy: Always
        env:
        - name: SID
          value: {{ $value  | quote }}
        ports:
        - containerPort: 10002
          name: server1
          protocol: TCP
        - containerPort: 10003
          name: server2
          protocol: TCP
        - containerPort: 10004
          name: server3
          protocol: TCP
        - containerPort: 10007
          name: server4
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: "/usr/data/svr/main_logic_real"
          subPath: main_logic_real
          readOnly: false
      volumes:
      - name: config
        configMap:
          # 提供你想要挂载的 ConfigMap 的名字
          name: roh5server-cm
          #defaultMode: 0777 
          # 来自 ConfigMap 的一组键，将被创建为文件
          items:
          - key: "main_logic_real"
            path: "main_logic_real"
---
{{- end }}
